camera_matrix:
  rows: 3
  cols: 3
  data: [615.0, 0.0, 320.0,
         0.0, 615.0, 240.0,
         0.0, 0.0, 1.0]

distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.1, -0.05, 0.0, 0.0, 0.0]

image_width: 640
image_height: 480

# 카메라와 로봇 베이스 간 변환 행렬 (예: 4x4)
camera_to_robot_transform:
  rows: 4
  cols: 4
  data: [
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.3,
    0.0, 0.0, 0.0, 1.0
  ]
